[package]
name = "oreo-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[features]
default = []
pocket-tts = []
vosk-stt = ["dep:vosk"]

[dependencies]
cpal.workspace = true
oreo-core = { path = "../oreo-core" }
rubato.workspace = true
vosk = { workspace = true, optional = true }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
