[package]
name = "oreo-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
oreo-local-api = { path = "../../crates/oreo-local-api" }
oreo-state = { path = "../../crates/oreo-state" }

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true

[[bin]]
name = "oreo-daemon"
path = "src/main.rs"
